### ISSUE TITLE
v2.0.0 todo list

### ISSUE THREAD

**Issue by happiness9721** [happiness9721/line-bot-sdk-swift#1]
- [x] add other reply message api
  - [x] reply Video message
  - [x] reply Audio message
  - [x] reply Location message
  - [x] reply Sticker message
  - [x] reply Imagemap message
  - [x] reply Template message
- [x] add push message function
- [x] add validation of channel secret
